#pragma once

// Generated For PUBGM! - NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (4.0.0) 
//SDK GENERATED BY @D_V_4

namespace SDK
{
//---------------------By ARMP---------------------------
//Enums
//---------------------By ARMP---------------------------

// Enum PixUIProfiler.EPxProfilerCapability
enum class EPxProfilerCapability : uint8_t
{
	EPxProfilerCapability__PrintSizeChange = 0,
	EPxProfilerCapability__PrintCountChange = 1,
	EPxProfilerCapability__AsyncInnerData = 2,
	EPxProfilerCapability__Count   = 3,
	EPxProfilerCapability__EPxProfilerCapability_MAX = 4
};



}

